### ISSUE TITLE
Investigate the MAML add-on

### ISSUE THREAD

**Issue by PsiPhiTheta** [PsiPhiTheta/catch-me-if-you-can#26]
As for MAML, Roger says he struggles to see when/where it could be used well for this task. It wouldn’t really make sense because we have such few examples with such few sigs for each that MAML might just end up memorising the dataset… I guess if we don't end up using it we just have to explain why it didn’t work (and alter the intro somewhat but its OK to leave it in the literature review)

**Comment by sometimescasey** [comment]
@PsiPhiTheta I assume we can close this given it's abandoned. Let me know if you want help writing the paper bit, otherwise I assume you've got this

**Comment by PsiPhiTheta** [comment]
Yeah, [I think I've got this](https://youtu.be/GEaYOx3JVO8?t=12)
